### ISSUE TITLE
Volt vs D

### ISSUE THREAD

**Issue by bubnenkoff** [VoltLang/Volta#10]
I see that Volt is very D-inspired. Could you add mention about difference? Maybe you can look at Nim to get more interesting futures to Volt?

**Comment by Wallbraker** [comment]
Yes it is, very much so as the compiler is written in D. The plan is to move it over to Volt in the near future and then diverge the language once we have a solid base to work from.

That said we have a old page with some differences written down: http://vp.dav1d.de/GfqR

It is old and a bit out of date so I have added a post on trello for it and comparison to C and C++ as well.

Hmm there probably is things we can take from Nim.

**Comment by bubnenkoff** [comment]
Thanks! I hope to see Volt to be more high level then D. Like D and C.
There is some tasks where there no need in C compatibility, just need productive language for writing different stuff.

Did you implemented Volt compiler from scratch? I ask because there is half-done products like https://github.com/deadalnix/SDC that can be easy hacked to getting them to new language.

**Comment by bhelyer** [comment]
Funnily enough, we took the lexer from SDC (incidentally, I am SDC's former maintainer ^^;). The rest of the code we mostly wrote ourselves because it didn't fit with Volt. (And the middle and back-end designs of SDC at that time were much worse before deadalnix took a chainsaw to them).

As far as new features go, probably the best way would be to open a specific new issue for each -- then Jakob, me, and whoever else can discuss if we feel they would be valuable and easily implementable etc etc.

**Comment by bubnenkoff** [comment]
Oh, yes, I see! You are SDC-man..)
That's very cool! Could you write about your motivation to creation of Volt?

**Comment by deadalnix** [comment]
I love chainsaw :)

**Comment by bhelyer** [comment]
I'm mostly focused with making things work -- Wallbraker is more the ideas man. :dancer:

**Comment by Wallbraker** [comment]
We are tracking the task of writing Volt vs X-Language in [Trello](https://trello.com/b/tnuM8Sjy/volt), no need for it here.
