### ISSUE TITLE
Coming from D guide

### ISSUE THREAD

**Issue by wilzbach** [VoltLang/Volta#19]
It would help a lot if you can provide a guide for people who already know D which explains the differences and (why those differences have been made)

**Comment by bhelyer** [comment]
Some aspects of syntax etc are still somewhat in the air, but this is definitely something we're interested in doing, and with more languages than just D. It's sitting on our Trello marked as 'minimal viable product', so we won't put out a 1.0 without such documentation being created.

**Comment by Wallbraker** [comment]
One some problem we have is that all developers know Volt pretty well, so we need somebody from the outside to point out most gotchas to us so we can put them down into a document. While we can supply a good basis ourselves we are bound to miss obvious stuff, just because its obvious to us.

**Comment by timotheecour** [comment]
something like https://github.com/timotheecour/D_vs_nim/ but with D_vs_volt

**Comment by Wallbraker** [comment]
That looks useful, thanks!

**Comment by ntrel** [comment]
Even a kept-up-to-date text file with terse items like 'static methods not visible on instance' would be v useful. There needs to be a maintained list with every significant deliberate change. Otherwise it's hard to see any language differences vs D.

**Comment by ntrel** [comment]
I've made a start [here](https://docs.google.com/document/d/18QF5EKIPsBP8uepFJGsGMJER0enHugT-wjRQzDp6axY/edit?usp=drivesdk).

**Comment by Wallbraker** [comment]
Thank you!

Turns out that @bhelyer added a comparison page to the excellent [TVPL](http://docs.volt-lang.org/doc/tvpl) he wrote [here](http://docs.volt-lang.org/doc/tvpl/a3-cf-to-d.html). But it was hidden away inside the book, I have now added direct links on [docs.volt-lang.org](http://docs.volt-lang.org/). The source for it is [here](https://github.com/VoltLang/Docs/blob/master/doc/tvpl/a3-cf-to-d.md) so feel free to file PRs to expand it with your notes.

**Comment by Wallbraker** [comment]
Closing issue as we now have a Volt vs D guide.

**Comment by ntrel** [comment]
Thanks for the links. I don't think the comparing Volt  with D page is selling Volt well to D programmers. (Templates are now implemented right? I like the version enhancement, type declaration syntax is ok but it's a significant C & D porting issue, `fn!CC` didn't seem interesting to me from that text, the TypeInfo change seems just different, not a clear advantage - it should explain why). 
I updated my doc a bit, I think a quick comparison of benefits is also useful rather than just listing changes in detail. I added a missing section. Does Volt have return type inference and struct destructors for RAII?
