### ISSUE TITLE
Function decorator bloat

### ISSUE THREAD

**Issue by bubnenkoff** [VoltLang/Volta#23]
[This](https://gist.github.com/ximion/77dda83a9926f892c9a4fa0074d6bf2b) post was about D, but it's seems that Volt have some same issue. example:
"Function decorator bloat: I recently tagged a function `@property @nogc pure @safe override`"

**Comment by Wallbraker** [comment]
We are looking into a way to make all functions in a module have a set of properties.

```
// Make all functions in this module @nogc and @system
default fn = @nogc @system;
```

`@property` is planned to be replaced with C# style properties
`@safe` is planned to be default
`pure` I'm not sure is needed in Volt
`override` will stay, it catches errors, maybe shorten the keyword. `ovrd` or something else.
`@nogc` will also stay, but with the default attribute per module shouldn't be that troublesome.

**Comment by r-k-o** [comment]
hi,
i was tipped to your project. I am trying to find some thing for me just as D1 and i am glad to see that you guys get rid of that @ - eye cancer. do have a time frame on when the compiler will be compiles downloadable as an exe for windows x64?
thanx

**Comment by Wallbraker** [comment]
Thanks!

Short answer in a couple of months you will be able to just install a VSCode extension and that would be that.

We have a CI that builds all of the needed executables (for windows) so if you feel adventures you can download battery and volta from there and have that work now. And using some manual work to get the VSCode extension working.

If you are IRC I recommend poking us in #volt on FreeNode. Or on one of the Twitter accounts [@Wallbraker](https://twitter.com/Wallbraker) or [@VoltLang](https://twitter.com/VoltLang). I would be happy to do some hand holding getting you setup.

**Comment by r-k-o** [comment]
thanks for the answer. will download and use.

**Comment by r-k-o** [comment]
https://ci.volt-lang.lv/ - doesn't work

**Comment by Wallbraker** [comment]
Oh it's on https://ci.walkyrie.se/

**Comment by r-k-o** [comment]
thanks

**Comment by r-k-o** [comment]
sorry for that, but where do i get llvm.dll or otheres in case they are needed?
thanks in advance for your patience.

**Comment by r-k-o** [comment]
ok, will do

**Comment by Wallbraker** [comment]
Oh make sure it's 64bit as we only support 64bit on windows.

**Comment by bhelyer** [comment]
If I could be forgiven some bikeshedding, I would like to be rid of the @ syntax for keywords entirely. If we need a keyword, we should add it. There's some stuff we could also clean up in regards to namespace issues -- we currently disallow member functions called 'init', as `T.init` gives you the default initialiser. Maybe this would be heresy, but we could just use `T.default` for that purpose, and get rid of that. Otherwise, making init a keyword would be my preference, but I don't see a reason we couldn't just appropriate `default` for that purpose.

**Comment by r-k-o** [comment]
_Oh make sure it's 64bit as we only support 64bit on windows._ 
yes

_I would like to be rid of the @ syntax for keywords entirely_ 
💯 
_If we need a keyword, we should add it. There's some stuff we could also clean up in regards to namespace issues -- we currently disallow member functions called 'init', as T.init gives you the default initialiser. Maybe this would be heresy, but we could just use T.default for that purpose, and get rid of that. Otherwise, making init a keyword would be my preference, but I don't see a reason we couldn't just appropriate default for that purpose._
 👍
